/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Bebida;
import classes.Ingrediente;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Thulio
 */
public class Tela extends javax.swing.JFrame {

    List<Bebida> bebidas = new ArrayList<>();
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        
        //teste
//        Bebida bebida = new Bebida();
//	bebida.setNome("TRINIDAD");
//	bebida.setInformacoes("Drink Frutado e muito saboroso, ideal para o cliente que queira drinks frutados ou de morango. Mulheres adoram!");
//	bebida.setSemAlcool(true);
//        bebida.setPreparo("CColoque a taça para gelar. Macere o morango com açúcar, acrescente o gin, limão e o xarope. Agite bastante com gelo. Coe na taça. Coloque a espuma de jabuticaba e salpique pimenta do reino.");
//	
//        List<Ingrediente> ingredientes = new ArrayList<Ingrediente>();
//            ingredientes.add(new Ingrediente("GIN","2", "oz"));
//            ingredientes.add(new Ingrediente("MORANGO","6", "unidades"));
//            ingredientes.add(new Ingrediente("SUCO DE LIMÃO","1/2", "oz"));
//            ingredientes.add(new Ingrediente("XAROPE DE PÊSSEGO OU FRAMBOESA","1/2", "oz"));
//            ingredientes.add(new Ingrediente("AÇÚCAR [OPCIONAL]","1/2", "colher"));
//            ingredientes.add(new Ingrediente("ESPUMA DE JABUTICABA","+", "+"));
//            ingredientes.add(new Ingrediente("PIMENTA DO REINO","+", "+"));
//        bebida.setIngredientes(ingredientes);
//        bebida.cadastrarBebida(bebida);
//        

        DefaultListModel modelolista = new DefaultListModel();
        Bebida x = new Bebida();
        bebidas = x.lerBebidas();
        
        for (Bebida b: bebidas){
            modelolista.addElement(b.getNome());
        }
        jListaBebidas.setModel(modelolista);
        
        //fim do teste
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaBebidas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnDetalhar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(":: MAIS BARTENDERS ::");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bartedner.png"))); // NOI18N

        jScrollPane1.setViewportView(jListaBebidas);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("BEBIDAS:");

        btnDetalhar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnDetalhar.setText("DETALHAR");
        btnDetalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDetalhar)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalhar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalharActionPerformed
        
        
        for (Bebida b:bebidas){
            if (b.getNome().equals(jListaBebidas.getSelectedValue())){
                
                String alc = (b.isSemAlcool()? "SIM":"NÃO");
                
                String ing = " ";
                for (Ingrediente i:b.getIngredientes()){
                    if (i.getUnidade().equals("+")){
                        ing += "- "+i.getNome() + "<br>";
                    }else{
                        ing += "- "+i.getQuantidade()+" "+i.getUnidade()+" de "+i.getNome() + "<br>";
                    }
                }
                
                
                JLabel dados = new JLabel("<html><body text-align:center; width='300'><center>"
                        + "<h1 style=\"color:red;\"><b>"+ b.getNome() + "</b></h1>"
                        + "<h2>- INFORMAÇÕES - </h2>"+b.getInformacoes() + "<br><br>"
                        + "<h2>- TEM ALCOOL - </h2><font size=\"5\" color=\"red\">"+alc + "</font><br><br>"
                        + "<h2>- PREPARO - </h2>"+b.getPreparo() + "<br><br>"
                        + "<h2>- INGREDIENTES - </h2>"+ing+"</center>");

                    ImageIcon image = new ImageIcon(getClass().getResource("/fotos/"+b.getNome().toLowerCase()+".jpg"));
                    
                    JLabel foto = new JLabel("", image, SwingConstants.CENTER);
                    
                    dados.setVerticalAlignment(SwingConstants.TOP);
                    

                    //foto.setBorder(BorderFactory.createLineBorder(Color.black));
                    //dados.setBorder(BorderFactory.createLineBorder(Color.black));

                    JFrame frame = new JFrame(":: DETALHES ::");
                    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    frame.setSize(335, 825);
                    frame.setResizable(false);
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                    
                    
                    JPanel p = new JPanel(new GridBagLayout());
                    frame.getContentPane().add(p, BorderLayout.NORTH);
                    GridBagConstraints c = new GridBagConstraints();
                    
                    c.fill = GridBagConstraints.BOTH;
                    c.gridx = 0;
                    c.gridy = 0;
                    c.ipadx = 15;
                    c.ipady = 25;
                    c.insets = new Insets(0, 0, 1, 0);
                    p.add(foto,c);
                    c.gridx = 0;
                    c.gridy = 1;
                    c.ipadx = 10;
                    c.ipady = 20;
                    p.add(dados,c);
            }
        }
        
        
    }//GEN-LAST:event_btnDetalharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalhar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListaBebidas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
